// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBN9eNlaMv7wDIP9NYgAu9Qep6cfmUhakM",
    authDomain: "flutter-login-app-e278b.firebaseapp.com",
    databaseURL: "https://flutter-login-app-e278b-default-rtdb.firebaseio.com",
    projectId: "flutter-login-app-e278b",
    storageBucket: "flutter-login-app-e278b.firebasestorage.app",
    messagingSenderId: "696544803362",
    appId: "1:696544803362:web:25a1550a0d840aec07a87b",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSJnQt0mCQRgvDNkRR-WgfIUgxMJxN1OQ',
    appId: '1:696544803362:android:1bbed99467b8f7c207a87b',
    messagingSenderId: '696544803362',
    projectId: 'flutter-login-app-e278b',
    databaseURL: 'https://flutter-login-app-e278b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-e278b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ4fMVNnRT5mUt-0zFt3OMQUJ2XupZDVk',
    appId: '1:696544803362:ios:b029fa5e8257df3d07a87b',
    messagingSenderId: '696544803362',
    projectId: 'flutter-login-app-e278b',
    databaseURL: 'https://flutter-login-app-e278b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-app-e278b.firebasestorage.app',
    iosClientId:
        '696544803362-7ghhdj2b1gien4tor5p7p0optl96tvs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.studydesign2zzdatabaseplaylist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBN9eNlaMv7wDIP9NYgAu9Qep6cfmUhakM",
    authDomain: "flutter-login-app-e278b.firebaseapp.com",
    databaseURL: "https://flutter-login-app-e278b-default-rtdb.firebaseio.com",
    projectId: "flutter-login-app-e278b",
    storageBucket: "flutter-login-app-e278b.firebasestorage.app",
    messagingSenderId: "696544803362",
    appId: "1:696544803362:web:29ad0e6f3b2dd0db07a87b",
  );
}
